const friend = {
  input: "friend",
  arguments: [
    "harrison",
    "flepio",
    "jay",
    "joe",
    "pin",
    "santi",
    "steph",
    "tim",
  ],
  output: {
    harrison: [
      null,
      "harrison doesn't have anything here yet...",
      null,
      `[ https://jonathan-vu.dev ]:`,
    ],
    flepio: [
      null,
      "jon: what's happening @Flepio",
      "Flepio: what is it",
      null,
      "jon has joined the call.",
      "Flepio has joined the call.",
      null,
      "Flepio: gotta run",
      null,
      "Flepio has left the call.",
      null,
      `[ https://jonathan-vu.dev ]:`,
    ],
    jay: [null, "(╯°□°)╯︵ ┻━┻ ", null, `[ https://jonathan-vu.dev ]:`],
    joe: [
      null,
      "joe doesn't have anything here yet...",
      null,
      `[ https://jonathan-vu.dev ]:`,
    ],
    pin: [
      null,
      ".========================================================================.",
      "|        F   `-._                                                       J|",
      "|       J        `-._                                                   F|",
      "|       |       J    `-.                                                L|",
      "|--...__|_      |     F `-.                                            J |",
      "|       F ```-- L..  J    J`-._                                        | |",
      "|      J       J   `-|-.. |   J`-.___                                  L |",
      "|      J       |     |   `|--.|__|   ````````------......_______...--- F |",
      "|      |       |     |    |   |  F                                    J  |",
      "|```---|--.... L.    L    L   | J                                     |  |",
      "|      |      J  ```J----J-...L_|                                     |  |",
      "|      F      J     |    J   J  |       _..__    --======..______     |  |",
      "|      L      J     |    |   |  |      /'    |     |/ / /:   ||       '  |",
      "|------L----..|.....J....|__ L_ F      L.____)     |/ / /:   ||       |  |",
      "|     J       |     |    |  J  J       (-(- c| -.  |/ / /:   ||       |  |",
      "|     |       |     L    L  |__|       /    |    `-. ___ :   ||       F  |",
      "|     |       L  __J.---J'''|  |        |_.'        :    )___|'          |",
      "|     |__..--J-''  |    |  _|-''_...  __|   jon      |               J   |",
      "|---''F      |     |    |-'_:-'' _. ,'   |  -._.|     |              ,   |",
      "|     L      |     L_.-':-'  _.-'  /      :      |     :             |   |",
      "|    J       L _.-J  .-'  .-'   _ /    )         .`.   )  _          |   |",
      "|    |     .J-'   :-'   .'.--.   /    /       --'   |  `   ```----...'   |",
      "|    | _.-' |   .'    .'  v-_ `-'  _.' |. (epi)     |  |             |   |",
      "|-_.-:'     | .'    .'       `; _)/     `-._{      .|  :             J   |",
      "|'   |      |(    .'   ___    `._J     . /  |   `./ L  }>             L  |",
      "|    |      |`.  (   ____  . .  _.  ) . /   L   _/  `--'              J  |",
      "|    |    .-'  |-.`    ___ |  |._ -' . /    (    (                    `L |",
      "|    | .-'      `.`-._      `-._   .' /      |   J                     ` |",
      "|    .'          )    `-._  ._ _.-' .'        )  |                      `|",
      "| .-'           (_..--..  `-..___.-'         / ` ))                      |",
      "|                       `-.      .'       ,-'/,  /                       |",
      "|                          `.   /         {.pin,'                        |",
      "|                            | |                                         |",
      "|                            (_)                   ._                    |",
      "|                                                 F  ` -..__             |",
      "|                                                J         | `-- .__     |",
      "|                                                F  `--.. _F       |`--..|",
      "|                                               J         J `--..__|_    |",
      "`a:f====================================================================='",

      null,
      `[ https://jonathan-vu.dev ]:`,
    ],
    santi: [
      null,
      "santi doesn't have anything here yet...",
      null,
      `[ https://jonathan-vu.dev ]:`,
    ],
    steph: [
      null,
      "steph doesn't have anything here yet...",
      null,
      `[ https://jonathan-vu.dev ]:`,
    ],
    tim: [
      null,
      "tim doesn't have anything here yet...",
      null,
      `[ https://jonathan-vu.dev ]:`,
    ],
  },
  error: [
    null,
    "You must provide a valid argument",
    null,
    "friend --harrison",
    null,
    "available friends:",
    "harrison, flepio, jay, joe, pin, santi, steph",
    "tim",
    null,
    `[ https://jonathan-vu.dev ]:`,
  ],
};

export { friend };
